### ISSUE TITLE
update-moab should copy files into the moab directory using a "normal" copying operation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_robots#405] opened 2022-06-28 00:25 UTC
The `update-moab` step in the preservationIngestWF does the following:

- starts in a state where new files to be added to a moab are located in a directory at `/pres-0#/deposit/druid`
- creates a new `v00#` folder for the new version being added to the moab
- copies the files from the deposit folder into the new version folder in the moab
- creates manifest files for the new moab folder

This issue is for changing the way `update-moab` performs the copying operation from the deposit folder to the druid's moab folder. The current "copying" method appears to be:

- create a hardlink between each file in the deposit folder and in the v00# moab folder
- remove the link to the file in the deposit folder, leaving only the link to the file in the v00# moab folder

At one point in the past this method may have saved time by effectively functioning like an `mv` within the boundaries of a single filesystem, meaning that no data would have been copied and only the paths would have been updated. But in our current storage, and I believe even in our pre-Ceph storage as of 2019, the underlying filesystem abstraction behind preservation storage means that data is actually being copied (i.e. new bytes are written) from one place to another when this step runs.

Changing this step to be an explicit copying operation would have these benefits:

- it would be more transparent to people trying to figure out what's going on at this step
- it would enable checking whether a copy is complete based on whether the file size of the new copy in the v00# moab folder matches the size of the copy in the deposit folder
- it would leave the files in the deposit folder at rest, unlike the hardlink strategy which implicates both the deposit file and the v00# moab file subject to the same operations once they've been linked

I suspect that problems we've seen with data corruption following preservation robots reboots are related to the hardlink/unlink behavior. We know from the `validate-bag` step that the files in the deposit folder must be valid before `update-moab` runs. But we've seen cases where files in the `deposit` folder are corrupt after `update-moab` is interrupted because of preservation issues. Using a file copying operation may not prevent the new copy from being corrupted in transit, but it should prevent already-copied good data from becoming bad and make it easier to remediate when that happens.

The hardlink/unlink behavior also seems to have the effect that the filesystem metadata for the files being copied this way never changes. That is, if you run `ls -l` on a file that goes through the hardlink process, the result will be the same for the path to the file in the deposit folder and the path in the v00# folder - even when the file hasn't been fully copied to the location referred to in the v00# path. 

So the tl;dr of this is: if we copy files using a copying method, it should be easier to tell if the new copy was made correctly.

**Comment by andrewjbtw** [comment] 2022-06-28 01:29
Taking this one step further: if it become possible to detect failures within the `update-moab` step itself, then we should make sure that retrying the step will result in re-copying the data without requiring manual filesystem cleanup. In our current state, `update-moab` never seems to fail. Instead, some things go wrong that could only have gone wrong at `update-moab` but we don't find out until one or more files fails validation at `validate-moab`.

My guess is that we don't detect `update-moab` problems because the hardlink/unlink behavior obscures what's happening at a lower level on the underlying storage, and to the filesystem abstraction it doesn't look like a file has been copied at all. Since `update-moab` doesn't currently fail, it can't be retried via Argo (which only enables retries on errors), and even if it could be retried it would fail because the data in the deposit folder would be corrupt at that point.

**Comment by julianmorley** [comment] 2022-06-28 17:05
The old `mv` method was fine and sane on a POSIX filesystem, but CephFS isn't native POSIX: it overlays POSIX semantics on top of the RADOS object store. So whilst it does support `mv`, it doesn't support it in a way that guarantees the same level of speed and certainty that messing with inode blocks on ext3 does. The hardlink-then-delete-original workflow is actually a rather expensive MDS operation, involving the creation of a new RADOS object, linking it to the old RADOS object, then in very short order removing that link. Add to that the speed and frequency with which this operation occurs and the MDS and/or client occasionally stumble, resulting in situations where either the client or the MDS need restarting in order for the files to appear correctly.

Doing a `cp` instead of `mv` removes this background object creation/edit/deletion process and should hopefully reduce the incidence of stale/unreadable metadata appearing on the `pres` mounts.

**Comment by ndushay** [comment] 2022-06-28 17:50
tagging @jmartin-sul here - 

also pondering if:
- this is an FR thing;  if not, is it a priority in the work cycle?
- this relates to any existing open tickets for pres-robots

**Comment by julianmorley** [comment] 2022-06-28 18:05
It definitely relates to #307 and probably #277.

**Comment by jmartin-sul** [comment] 2022-06-29 22:47
As @julianmorley pointed out on Slack, there's already (sort of) an option for this.  However, the parameter that toggles the hardlinking behavior is buried in the moab-versioning gem methods in a way that makes it inaccessible to consumers of the moab-versioning gem (at least as we use the gem).  I filed https://github.com/sul-dlss/moab-versioning/issues/200 for making the parameter accessible.  I think that moab-versioning ticket blocks this ticket.

See also https://github.com/sul-dlss/preservation_robots/blob/da609e494bd91511b65649cc4134f74325ff885e/lib/robots/sdr_repo/preservation_ingest/update_moab.rb#L26

I think that is the moab-versioning call that will get updated in pres robots once the aforementioned moab-versioning ticket is done.

In terms of testing for this issue, I'd suggest that we do something like:
* Run [create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) 10 times.  Make sure that most runs succeed, and that any failed runs are investigated, and that the failures are not attributable to the change in hardlinking behavior.  This spec exercises accessioning and versioning, with a check to make sure that the object made it through to successful replication for both versions, to all 3 cloud endpoints.  If it passes consistently, that's a good indication that creating new preservation versions is working correctly.  Maybe also run the test objects through pres cat's checksum validation if we want to be extra paranoid.
* Test accessioning a multi-version object that has some large files.
* Test accessioning a multi-version object that has a large number of small files.

Unfortunately, this is very hard to test as realistically as we'd like outside of production, as production is the only env in which preservation storage is backed by Ceph.  But based on @julianmorley's speculation, it seems like we can be reasonably confident that if this is working in a normal POSIX environment, it should also work fine for Ceph? :shrug:

We probably also want to keep an eye on the first few objects that go through preservation after this change is deployed, so that we can check them to make sure they look ok (e.g. run checksum validation on some gbooks that come through after this is deployed, or similar).

**Comment by ndushay** [comment] 2022-07-07 05:07
Actions for this ticket at this time:
- [ ] use moab-versioning v5.1.0, which I just released to get access to this change: PR sul-dlss/moab-versioning/issues/200
- [ ] change lib/robots/sdr_repo/preservation_ingest/update_moab.rb#L26 ... add the newly available param to not use hard_links  (set it to `false` -- you can follow the code chain from PR sul-dlss/moab-versioning/pull/202 to sul-dlss/moab-versioning/blob/main/lib/moab/storage_object_version.rb#L179
- [ ] for testing in situ, see John's comment above.  Also coordinate with Andrew.

**Comment by ndushay** [comment] 2022-07-07 17:08
@andrewjbtw - assigning this to you as you now need to test it and ensure we haven't made anything worse.

**Comment by jmartin-sul** [comment] 2022-07-08 00:59
i ran the `create_preassembly_image_spec.rb` testing described above, and that went fine.  ran 12 times between about 10 am and 5:30 pm today in between doing other things.

i hit a couple failures between 10:30 and 11 am, but due to jp2 create issues from common-accessioning like [`Permission denied @ rb_sysopen - /imtmp/assembly-image20220707-2230666-3x5w2a.tif`](https://app.honeybadger.io/projects/52894/faults/86596389), which don't have anything to do with this change.

so if @andrewjbtw signs off on this with his manual testing, i think this is good to go?

**Comment by jmartin-sul** [comment] 2022-07-08 01:02
side-note:  even on non-ceph systems, accessioning two versions in a row very quickly can sometimes fail unexpectedly when the second version is being written (this has caused intermittent and hard to reproduce test failures in the past).  it wouldn't shock me to not run into that after a dozen executions of create_preassembly_image_spec, but it does surprise me a little that i didn't hit that.  it would be nice if the switch to a regular file copy also stopped that problem from occurring. (@andrewjbtw can correct me if i'm mis-remembering this, as i think he's observed the problem i'm describing)

**Comment by jmartin-sul** [comment] 2022-07-08 19:10
@andrewjbtw said on slack: "Switching to a copy action will go out next week, assuming we don’t find any issue in stage today. Testing has looked good."

not sure if that means there's remaining testing to do?  if not, i think this can be closed.

**Comment by andrewjbtw** [comment] 2022-07-08 19:59
I'm running another couple of test objects today.

**Closed** 2022-07-12 18:05 UTC
Labels: bug, tech debt, performance, hold for PO review, SDR improvements
